---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests:
      storage: "1Gi"
  storageClassName: gp2
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - image: mysql:8
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootroot"
    - name: MYSQL_DATABASE
      value: "openmrs"
    - name: MYSQL_USER
      value: "eswar"
    - name: MYSQL_PASSWORD
      value: "Eswar@29"  
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-vol
  volumes:
  - name: mysql-vol
    persistentVolumeClaim:
      claimName: mysql-pvc    
