---
apiVersion: v1 
kind: Service
metadata:
  name: gol-svc
spec:
  type: NodePort
  selector:
    app: gol-p
    version: "1.0"
  ports:
  - name: gol-port
    nodePort: 30111 
    port: 80
    targetPort: 8080
  
   